- name: create users
  hosts: 
   - local
  vars: 
   users:
     - ab
     - ac
     - ad
     - jawza
     - jem
     - jemini
  tasks:
    - name: create  users
      user:
        name: "{{item}}"
        state: absent
      loop: "{{users}}"
      become: true